name: Go package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          check-latest: true
  
      - name: Build
        run: go build -v -o bin/ tailscale.com/cmd/tailscale{,d}
        env:
          GOOS: windows
          GOARCH: amd64

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: tailscale-win64
          path: bin/
